import XCTest
@testable import CosmoOS

/// Pure parsing contracts for the free-transcript pipeline: video-id
/// extraction, caption-track selection from a watch page, json3 events, and
/// paragraph grouping.
final class YouTubeTranscriptServiceTests: XCTestCase {

    // MARK: - Video id extraction

    func testVideoIDFromCommonURLShapes() {
        XCTAssertEqual(YouTubeTranscriptService.videoID(from: "https://www.youtube.com/watch?v=abc123XYZ_-"), "abc123XYZ_-")
        XCTAssertEqual(YouTubeTranscriptService.videoID(from: "https://youtu.be/abc123XYZ_-"), "abc123XYZ_-")
        XCTAssertEqual(YouTubeTranscriptService.videoID(from: "https://www.youtube.com/watch?v=abc&t=120s"), "abc")
        XCTAssertEqual(YouTubeTranscriptService.videoID(from: "https://www.youtube.com/embed/abc123"), "abc123")
        XCTAssertNil(YouTubeTranscriptService.videoID(from: "https://example.com/watch?x=1"))
    }

    // MARK: - Caption track selection

    func testManualEnglishTrackBeatsAutoGenerated() {
        let html = """
        junk before "captionTracks":[{"baseUrl":"https://yt/asr\\u0026lang=en","languageCode":"en","kind":"asr"},{"baseUrl":"https://yt/manual\\u0026lang=en","languageCode":"en"}] junk after
        """
        let url = YouTubeTranscriptService.bestCaptionTrackURL(inWatchPage: html)
        XCTAssertEqual(url, "https://yt/manual&lang=en", "Manual captions outrank auto-generated")
    }

    func testAutoGeneratedIsUsedWhenNothingElseExists() {
        let html = #""captionTracks":[{"baseUrl":"https://yt/asr","languageCode":"en","kind":"asr"}]"#
        XCTAssertEqual(YouTubeTranscriptService.bestCaptionTrackURL(inWatchPage: html), "https://yt/asr")
    }

    func testPageWithoutCaptionsYieldsNil() {
        XCTAssertNil(YouTubeTranscriptService.bestCaptionTrackURL(inWatchPage: "<html>no captions here</html>"))
    }

    // MARK: - json3 parsing

    func testParseJSON3ReadsEventsAndSkipsEmpties() {
        let json = """
        {"events":[
            {"tStartMs":0,"segs":[{"utf8":"Hello "},{"utf8":"world"}]},
            {"tStartMs":2500,"segs":[{"utf8":"\\n"}]},
            {"tStartMs":5000,"segs":[{"utf8":"Second line"}]}
        ]}
        """
        let segments = YouTubeTranscriptService.parseJSON3(Data(json.utf8))
        XCTAssertEqual(segments.count, 2)
        XCTAssertEqual(segments[0].text, "Hello world")
        XCTAssertEqual(segments[0].start, 0)
        XCTAssertEqual(segments[1].start, 5.0, accuracy: 0.001)
    }

    // MARK: - srv3 parsing (InnerTube ANDROID caption format)

    func testParseSRV3ReadsPlainAndWordSegmentedParagraphs() {
        // Shape captured from a real InnerTube ANDROID caption body: plain
        // paragraphs, whitespace-only filler paragraphs, and ASR paragraphs
        // holding per-word <s> elements.
        let xml = """
        <?xml version="1.0" encoding="utf-8" ?><timedtext format="3">
        <head><ws id="0"/><wp id="0"/></head>
        <body>
        <w t="0" id="1" wp="1" ws="1"/>
        <p t="1360" d="1680">[Music]</p>
        <p t="18790" w="1" a="1">
        </p>
        <p t="18800" d="7160" w="1"><s ac="0">We&#39;re</s><s t="239" ac="0"> no</s><s t="559" ac="0"> strangers</s></p>
        <p t="22640" d="4320">You know the rules
        and so do I</p>
        </body>
        </timedtext>
        """
        let segments = YouTubeTranscriptService.parseSRV3(Data(xml.utf8))
        XCTAssertEqual(segments.count, 3, "Filler paragraphs are dropped")
        XCTAssertEqual(segments[0].text, "[Music]")
        XCTAssertEqual(segments[0].start, 1.36, accuracy: 0.001)
        XCTAssertEqual(segments[0].duration ?? 0, 1.68, accuracy: 0.001)
        XCTAssertEqual(segments[1].text, "We're no strangers")
        XCTAssertEqual(segments[1].start, 18.8, accuracy: 0.001)
        XCTAssertEqual(segments[2].text, "You know the rules and so do I")
    }

    func testParseTrackHandlesEitherFormat() {
        let json3 = #"{"events":[{"tStartMs":0,"segs":[{"utf8":"hi"}]}]}"#
        XCTAssertEqual(YouTubeTranscriptService.parseTrack(Data(json3.utf8)).first?.text, "hi")
        let srv3 = #"<timedtext format="3"><body><p t="0" d="1000">hello</p></body></timedtext>"#
        XCTAssertEqual(YouTubeTranscriptService.parseTrack(Data(srv3.utf8)).first?.text, "hello")
        XCTAssertTrue(YouTubeTranscriptService.parseTrack(Data()).isEmpty, "Empty body yields no segments")
    }

    // MARK: - InnerTube track selection

    func testBestTrackPrefersManualEnglishThenManualThenASR() {
        func track(_ lang: String?, _ kind: String?) -> YouTubeCaptionTrack {
            // Decodable-only struct: build via JSON like production does.
            let json = """
            {"baseUrl":"https://yt/\(lang ?? "none")-\(kind ?? "manual")",
             "languageCode":\(lang.map { "\"\($0)\"" } ?? "null"),
             "kind":\(kind.map { "\"\($0)\"" } ?? "null")}
            """
            return try! JSONDecoder().decode(YouTubeCaptionTrack.self, from: Data(json.utf8))
        }
        let asrEnglish = track("en", "asr")
        let manualGerman = track("de", nil)
        let manualEnglish = track("en-US", nil)

        XCTAssertEqual(
            YouTubeTranscriptService.bestTrack(in: [asrEnglish, manualGerman, manualEnglish])?.baseUrl,
            manualEnglish.baseUrl
        )
        XCTAssertEqual(
            YouTubeTranscriptService.bestTrack(in: [asrEnglish, manualGerman])?.baseUrl,
            manualGerman.baseUrl
        )
        XCTAssertEqual(
            YouTubeTranscriptService.bestTrack(in: [asrEnglish])?.baseUrl,
            asrEnglish.baseUrl
        )
        XCTAssertNil(YouTubeTranscriptService.bestTrack(in: []))
    }

    // MARK: - Paragraph grouping

    func testParagraphsGroupByTimeAndLength() {
        var segments: [YouTubeTranscriptSegment] = []
        for index in 0..<20 {
            segments.append(.init(start: Double(index * 10), text: "Sentence \(index) with some words."))
        }
        let paragraphs = YouTubeTranscriptService.paragraphs(from: segments, maxSeconds: 45, maxCharacters: 420)
        XCTAssertGreaterThan(paragraphs.count, 1, "Long transcripts break into passages")
        XCTAssertEqual(paragraphs.first?.start, 0)
        // The window flushes after the segment that crosses it (0–50 inclusive),
        // so the second passage starts at 60.
        XCTAssertEqual(paragraphs[1].start, 60, accuracy: 0.001)
        // Nothing is lost.
        let recombined = paragraphs.map(\.text).joined(separator: " ")
        XCTAssertTrue(recombined.contains("Sentence 0"))
        XCTAssertTrue(recombined.contains("Sentence 19"))
    }

    func testTimestampLabelFormats() {
        XCTAssertEqual(YouTubeTranscriptParagraph(id: 0, start: 65, text: "x").timestampLabel, "1:05")
        XCTAssertEqual(YouTubeTranscriptParagraph(id: 0, start: 3725, text: "x").timestampLabel, "1:02:05")
    }
}
