#!/bin/bash

# CosmoOS Release Build Script
# Builds using the native Xcode Project generated by XcodeGen
# This ensures correct Entitlements and Signing for Apple Intelligence

set -e  # Exit on any error

echo "🚀 Building CosmoOS (Native Project)..."

# Navigate to project directory
cd "$(dirname "$0")"

# Clean previous builds
rm -rf CosmoOS.app 2>/dev/null
rm -rf .build/DerivedData 2>/dev/null

# Build using xcodebuild with the Project
echo "📦 Compiling with xcodebuild..."

DERIVED_DATA_PATH=".build/DerivedData"
# Note: When building a Project, the output path is slightly different usually
PRODUCTS_DIR="$DERIVED_DATA_PATH/Build/Products/Release"

xcodebuild build \
    -project CosmoOS.xcodeproj \
    -scheme CosmoOS \
    -configuration Release \
    -derivedDataPath "$DERIVED_DATA_PATH" \
    -destination 'platform=macOS' \


echo "✅ Build successful!"

# Move the built app to the root directory
if [ -d "$PRODUCTS_DIR/CosmoOS.app" ]; then
    echo "📁 Copying CosmoOS.app to root..."
    cp -R "$PRODUCTS_DIR/CosmoOS.app" .
else
    echo "❌ Build passed but CosmoOS.app not found at $PRODUCTS_DIR/CosmoOS.app"
    exit 1
fi

APP_DIR="CosmoOS.app/Contents"

# Verify Entitlements
echo ""
echo "🔐 Verifying Entitlements..."
if codesign -d --entitlements - CosmoOS.app 2>&1 | grep -q "com.apple.developer.intelligence-platform.api"; then
    echo "   ✅ CRITICAL: Intelligence Entitlement found!"
else
    echo "   ⚠️  WARNING: Intelligence Entitlement MISSING. Voice commands may hang."
fi

echo ""
echo "✨ CosmoOS.app created successfully!"
echo ""
echo "📍 Location: $(pwd)/CosmoOS.app"
echo ""
echo "🎯 To run:"
echo "   open CosmoOS.app"
echo ""
echo "⚠️  IMPORTANT: For voice commands to work:"
echo "   1. Open System Settings → Privacy & Security → Accessibility"
echo "   2. Click '+' and add CosmoOS.app"
echo "   3. Restart CosmoOS"
echo ""
echo "🎤 For voice commands:"
echo "   1. Open System Settings → Privacy & Security → Microphone"
echo "   2. Allow CosmoOS"
echo ""
echo "🧠 Apple Foundation Models (Neural Engine) ready"
echo "   - If you have macOS 15.2+ and Apple Silicon, voice commands will use the Neural Engine"
echo "   - Check System Settings → Apple Intelligence & Siri to enable Apple Intelligence"
echo ""
echo "Ready to launch? Run: open CosmoOS.app"
